//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication1.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginRecepcionistOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback allClientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataRecepcionistOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback DataReserveIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback addReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback delReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateReserveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::WebApplication1.Properties.Settings.Default.WebApplication1_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event LoginRecepcionistCompletedEventHandler LoginRecepcionistCompleted;
        
        /// <remarks/>
        public event LoginClientCompletedEventHandler LoginClientCompleted;
        
        /// <remarks/>
        public event allClientsCompletedEventHandler allClientsCompleted;
        
        /// <remarks/>
        public event DataRecepcionistCompletedEventHandler DataRecepcionistCompleted;
        
        /// <remarks/>
        public event DataClientCompletedEventHandler DataClientCompleted;
        
        /// <remarks/>
        public event DataReserveCompletedEventHandler DataReserveCompleted;
        
        /// <remarks/>
        public event DataReserveIdCompletedEventHandler DataReserveIdCompleted;
        
        /// <remarks/>
        public event addReserveCompletedEventHandler addReserveCompleted;
        
        /// <remarks/>
        public event delReserveCompletedEventHandler delReserveCompleted;
        
        /// <remarks/>
        public event updateReserveCompletedEventHandler updateReserveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginRecepcionist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoginRecepcionist(int idn) {
            object[] results = this.Invoke("LoginRecepcionist", new object[] {
                        idn});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoginRecepcionistAsync(int idn) {
            this.LoginRecepcionistAsync(idn, null);
        }
        
        /// <remarks/>
        public void LoginRecepcionistAsync(int idn, object userState) {
            if ((this.LoginRecepcionistOperationCompleted == null)) {
                this.LoginRecepcionistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginRecepcionistOperationCompleted);
            }
            this.InvokeAsync("LoginRecepcionist", new object[] {
                        idn}, this.LoginRecepcionistOperationCompleted, userState);
        }
        
        private void OnLoginRecepcionistOperationCompleted(object arg) {
            if ((this.LoginRecepcionistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginRecepcionistCompleted(this, new LoginRecepcionistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoginClient(int idn) {
            object[] results = this.Invoke("LoginClient", new object[] {
                        idn});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoginClientAsync(int idn) {
            this.LoginClientAsync(idn, null);
        }
        
        /// <remarks/>
        public void LoginClientAsync(int idn, object userState) {
            if ((this.LoginClientOperationCompleted == null)) {
                this.LoginClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginClientOperationCompleted);
            }
            this.InvokeAsync("LoginClient", new object[] {
                        idn}, this.LoginClientOperationCompleted, userState);
        }
        
        private void OnLoginClientOperationCompleted(object arg) {
            if ((this.LoginClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginClientCompleted(this, new LoginClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/allClients", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable allClients(int id) {
            object[] results = this.Invoke("allClients", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void allClientsAsync(int id) {
            this.allClientsAsync(id, null);
        }
        
        /// <remarks/>
        public void allClientsAsync(int id, object userState) {
            if ((this.allClientsOperationCompleted == null)) {
                this.allClientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnallClientsOperationCompleted);
            }
            this.InvokeAsync("allClients", new object[] {
                        id}, this.allClientsOperationCompleted, userState);
        }
        
        private void OnallClientsOperationCompleted(object arg) {
            if ((this.allClientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.allClientsCompleted(this, new allClientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DataRecepcionist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DataRecepcionist(int id) {
            object[] results = this.Invoke("DataRecepcionist", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DataRecepcionistAsync(int id) {
            this.DataRecepcionistAsync(id, null);
        }
        
        /// <remarks/>
        public void DataRecepcionistAsync(int id, object userState) {
            if ((this.DataRecepcionistOperationCompleted == null)) {
                this.DataRecepcionistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataRecepcionistOperationCompleted);
            }
            this.InvokeAsync("DataRecepcionist", new object[] {
                        id}, this.DataRecepcionistOperationCompleted, userState);
        }
        
        private void OnDataRecepcionistOperationCompleted(object arg) {
            if ((this.DataRecepcionistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataRecepcionistCompleted(this, new DataRecepcionistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DataClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DataClient(int id) {
            object[] results = this.Invoke("DataClient", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DataClientAsync(int id) {
            this.DataClientAsync(id, null);
        }
        
        /// <remarks/>
        public void DataClientAsync(int id, object userState) {
            if ((this.DataClientOperationCompleted == null)) {
                this.DataClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataClientOperationCompleted);
            }
            this.InvokeAsync("DataClient", new object[] {
                        id}, this.DataClientOperationCompleted, userState);
        }
        
        private void OnDataClientOperationCompleted(object arg) {
            if ((this.DataClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataClientCompleted(this, new DataClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DataReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DataReserve(int id, int rol) {
            object[] results = this.Invoke("DataReserve", new object[] {
                        id,
                        rol});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DataReserveAsync(int id, int rol) {
            this.DataReserveAsync(id, rol, null);
        }
        
        /// <remarks/>
        public void DataReserveAsync(int id, int rol, object userState) {
            if ((this.DataReserveOperationCompleted == null)) {
                this.DataReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataReserveOperationCompleted);
            }
            this.InvokeAsync("DataReserve", new object[] {
                        id,
                        rol}, this.DataReserveOperationCompleted, userState);
        }
        
        private void OnDataReserveOperationCompleted(object arg) {
            if ((this.DataReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataReserveCompleted(this, new DataReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DataReserveId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DataReserveId(int id, int idRecepcionist) {
            object[] results = this.Invoke("DataReserveId", new object[] {
                        id,
                        idRecepcionist});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DataReserveIdAsync(int id, int idRecepcionist) {
            this.DataReserveIdAsync(id, idRecepcionist, null);
        }
        
        /// <remarks/>
        public void DataReserveIdAsync(int id, int idRecepcionist, object userState) {
            if ((this.DataReserveIdOperationCompleted == null)) {
                this.DataReserveIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDataReserveIdOperationCompleted);
            }
            this.InvokeAsync("DataReserveId", new object[] {
                        id,
                        idRecepcionist}, this.DataReserveIdOperationCompleted, userState);
        }
        
        private void OnDataReserveIdOperationCompleted(object arg) {
            if ((this.DataReserveIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DataReserveIdCompleted(this, new DataReserveIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addReserve(int idRecepcionist, int idClient, string arrivalDate, string finishDate, string typeRoom) {
            this.Invoke("addReserve", new object[] {
                        idRecepcionist,
                        idClient,
                        arrivalDate,
                        finishDate,
                        typeRoom});
        }
        
        /// <remarks/>
        public void addReserveAsync(int idRecepcionist, int idClient, string arrivalDate, string finishDate, string typeRoom) {
            this.addReserveAsync(idRecepcionist, idClient, arrivalDate, finishDate, typeRoom, null);
        }
        
        /// <remarks/>
        public void addReserveAsync(int idRecepcionist, int idClient, string arrivalDate, string finishDate, string typeRoom, object userState) {
            if ((this.addReserveOperationCompleted == null)) {
                this.addReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddReserveOperationCompleted);
            }
            this.InvokeAsync("addReserve", new object[] {
                        idRecepcionist,
                        idClient,
                        arrivalDate,
                        finishDate,
                        typeRoom}, this.addReserveOperationCompleted, userState);
        }
        
        private void OnaddReserveOperationCompleted(object arg) {
            if ((this.addReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addReserveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void delReserve(int id) {
            this.Invoke("delReserve", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void delReserveAsync(int id) {
            this.delReserveAsync(id, null);
        }
        
        /// <remarks/>
        public void delReserveAsync(int id, object userState) {
            if ((this.delReserveOperationCompleted == null)) {
                this.delReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OndelReserveOperationCompleted);
            }
            this.InvokeAsync("delReserve", new object[] {
                        id}, this.delReserveOperationCompleted, userState);
        }
        
        private void OndelReserveOperationCompleted(object arg) {
            if ((this.delReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delReserveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateReserve(int id, int idRecepcionist, int idClient, string arrivalDate, string finishDate, string typeRoom) {
            this.Invoke("updateReserve", new object[] {
                        id,
                        idRecepcionist,
                        idClient,
                        arrivalDate,
                        finishDate,
                        typeRoom});
        }
        
        /// <remarks/>
        public void updateReserveAsync(int id, int idRecepcionist, int idClient, string arrivalDate, string finishDate, string typeRoom) {
            this.updateReserveAsync(id, idRecepcionist, idClient, arrivalDate, finishDate, typeRoom, null);
        }
        
        /// <remarks/>
        public void updateReserveAsync(int id, int idRecepcionist, int idClient, string arrivalDate, string finishDate, string typeRoom, object userState) {
            if ((this.updateReserveOperationCompleted == null)) {
                this.updateReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateReserveOperationCompleted);
            }
            this.InvokeAsync("updateReserve", new object[] {
                        id,
                        idRecepcionist,
                        idClient,
                        arrivalDate,
                        finishDate,
                        typeRoom}, this.updateReserveOperationCompleted, userState);
        }
        
        private void OnupdateReserveOperationCompleted(object arg) {
            if ((this.updateReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateReserveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginRecepcionistCompletedEventHandler(object sender, LoginRecepcionistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginRecepcionistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginRecepcionistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginClientCompletedEventHandler(object sender, LoginClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void allClientsCompletedEventHandler(object sender, allClientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class allClientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal allClientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DataRecepcionistCompletedEventHandler(object sender, DataRecepcionistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataRecepcionistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataRecepcionistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DataClientCompletedEventHandler(object sender, DataClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DataReserveCompletedEventHandler(object sender, DataReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DataReserveIdCompletedEventHandler(object sender, DataReserveIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataReserveIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DataReserveIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addReserveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void delReserveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void updateReserveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591